# These are supported funding model platforms

patreon: Barimehdi77
ko_fi: barimehdi77
liberapay: Barimehdi77
issuehunt: barimehdi77
custom: 
      - "buymeacoffee.com/barimehdi77"
      - "https://paypal.me/barimehdi77"
